---
- name: Local
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Retrieve the loom binary
    command: curl -sL -o /tmp/loom-{{ loom_build }} https://private.delegatecall.com/loom/linux/{{ loom_build }}/loom creates=/tmp/loom-{{ loom_build }}

- name: Provision multi-node loom
  hosts: all
  gather_facts: yes
  connection: ssh

  roles:
    - loom
